// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbContext.Migrations.PostgresDbContext
{
    [DbContext(typeof(MainDbContext.PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtistDbMMusicGroupDbM", b =>
                {
                    b.Property<Guid>("ArtistsDbMArtistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MusicGroupsDbMMusicGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("ArtistsDbMArtistId", "MusicGroupsDbMMusicGroupId");

                    b.HasIndex("MusicGroupsDbMMusicGroupId");

                    b.ToTable("ArtistDbMMusicGroupDbM", "supusr");
                });

            modelBuilder.Entity("DbModels.AlbumDbM", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CopiesSold")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MusicGroupDbMMusicGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<bool>("Seeded")
                        .HasColumnType("boolean");

                    b.HasKey("AlbumId");

                    b.HasIndex("MusicGroupDbMMusicGroupId");

                    b.ToTable("Albums", "supusr");
                });

            modelBuilder.Entity("DbModels.ArtistDbM", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("boolean");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists", "supusr");
                });

            modelBuilder.Entity("DbModels.MusicGroupDbM", b =>
                {
                    b.Property<Guid>("MusicGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EstablishedYear")
                        .HasColumnType("integer");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("boolean");

                    b.Property<string>("strGenre")
                        .HasColumnType("varchar(200)");

                    b.HasKey("MusicGroupId");

                    b.ToTable("MusicGroups", "supusr");
                });

            modelBuilder.Entity("DbModels.UserDbM", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("Models.DTO.GstUsrInfoDbDto", b =>
                {
                    b.Property<int>("NrSeededAlbums")
                        .HasColumnType("integer");

                    b.Property<int>("NrSeededArtists")
                        .HasColumnType("integer");

                    b.Property<int>("NrSeededMusicGroups")
                        .HasColumnType("integer");

                    b.Property<int>("NrUnseededAlbums")
                        .HasColumnType("integer");

                    b.Property<int>("NrUnseededArtists")
                        .HasColumnType("integer");

                    b.Property<int>("NrUnseededMusicGroups")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("vwInfoDb", "gstusr");
                });

            modelBuilder.Entity("ArtistDbMMusicGroupDbM", b =>
                {
                    b.HasOne("DbModels.ArtistDbM", null)
                        .WithMany()
                        .HasForeignKey("ArtistsDbMArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.MusicGroupDbM", null)
                        .WithMany()
                        .HasForeignKey("MusicGroupsDbMMusicGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbModels.AlbumDbM", b =>
                {
                    b.HasOne("DbModels.MusicGroupDbM", "MusicGroupDbM")
                        .WithMany("AlbumsDbM")
                        .HasForeignKey("MusicGroupDbMMusicGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicGroupDbM");
                });

            modelBuilder.Entity("DbModels.MusicGroupDbM", b =>
                {
                    b.Navigation("AlbumsDbM");
                });
#pragma warning restore 612, 618
        }
    }
}
